# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO_VERSION=1.9.2
  - DJANGO_VERSION=1.8.9
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.5.12

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=1.5.12
    - python: "3.3"
      env: DJANGO_VERSION=1.9.2
    - python: "3.3"
      env: DJANGO_VERSION=1.7.11
    - python: "3.3"
      env: DJANGO_VERSION=1.6.11
    - python: "3.3"
      env: DJANGO_VERSION=1.5.12

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source cmsplugin_plain_text runtests.py

after_success:
  - codecov
